### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi-detect#676]
Python 3.11 came out on 27/10/22 so we should look to support it soon. However, as always, we're mainly limited by upstream support from `tensorflow` and `torch`:
 - [x] https://github.com/tensorflow/tensorflow/issues/58032 (PR included in tf 2.12).
 - [ ] https://github.com/pytorch/pytorch/issues/86566 (3.11 support, not including `torch.compile`, included in torch 2.0).
- [x] https://github.com/numba/numba/issues/8304 (PR merged, will be included in 0.57.0 according [to this](https://github.com/numba/numba/issues/8304#issuecomment-1480876090)).

**Comment by ascillitoe** [comment]
Adding `numba` to the list:
- [ ] https://github.com/numba/numba/issues/8304

This might actually be our main blocker since `torch` and `tensorflow` are optional now?

**Comment by jklaise** [comment]
@ascillitoe good point, however, I think we should wait before both `tensorflow` and `torch` are Python 3.11 compatible to claim that both our libraries are too given how extensively we use those two (also CI would fail since we install both by default to test everything).

**Comment by ascillitoe** [comment]
Ah yeh good point about CI!
